"""add user_id to posts

Revision ID: e35f682c06df
Revises: 
Create Date: 2025-11-27 20:42:22.987136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35f682c06df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Update existing posts to have a user_id (set to the first user's ID)
    # You may want to adjust this logic based on your requirements
    op.execute('UPDATE posts SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL')
    
    # Now make the column non-nullable
    op.alter_column('posts', 'user_id', nullable=False)
    
    # Add the foreign key constraint
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
